[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "thoughtframe-python"
version = "0.0.0"
dependencies = [
    "aiohttp"
]

[tool.setuptools]
packages = ["tf_core"]
